#pragma once

#define EVENT_READ_MODEL_FILE "L_EVENT_READ_MODEL_FILE"

#define EVENT_LOAD_NEW_MODEL "R_EVENT_LOAD_NEW_MODEL"
#define EVENT_LOAD_SHADER "R_EVENT_LOAD_SHADER"
#define EVENT_RENDER_MODEL "R_EVENT_RENDER_MODEL"

#define EVENT_SEND_UNIFORM_DATA "R_EVENT_SEND_UNIFORM_DATA"